base/urls.py
from django.urls import path
from base.views import index, dashboard

app_name = 'base'

urlpatterns = [
    path('', index, name='index'),
    path('dashboard/', dashboard, name='dashboard'),
]

meals/urls.py
from django.urls import path
from meals.views import meal_add, meal_delete, meal_detail, meal_edit

app_name = 'meals'

urlpatterns = [
    path('add/', meal_add, name='meal_add'),
    path('<int:pk>/', meal_detail, name='meal_detail'),
    path('<int:pk>/delete/', meal_delete, name='meal_delete'),
    path('<int:pk>/edit/', meal_edit, name='meal_edit'),

]

urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('categories/', include('categories.urls')),
    path('meals/', include('meals.urls')),
    path('products/', include('products.urls')),
    path('users/', include('users.urls')),
    path('', include('authentication.urls')),
    path('', include('base.urls')),
]

if settings.DEBUG:
    import debug_toolbar

    statics = static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) \
        + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

    urlpatterns += [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + statics

base/models.py
from django.db import models

# Create your models here.

base/views.py
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect
from django.shortcuts import render

from meals.models import Meal


@login_required
def dashboard(request):
    meals = Meal.objects.filter(user=request.user)
    return render(request, 'dashboard.html', {'meals': meals})


def index(request):
    if request.user.is_authenticated:
        return HttpResponseRedirect('dashboard/')
    else:
        return render(request, 'index.html', {'index': index})

templates/base.html
{% load static %}

{% load i18n %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    </head>

<body>

    <div id="main-wrapper">
        <div class="container-fluid">
            <div class="navbar-fixed">
                <div class="fix-width">
                    <div class="header">
                        <nav class="navbar navbar-expand-md navbar-light bg-white">
                            <a class="navbar-brand" href="{% url 'base:index' %}">
                                <img src="{% static 'images/logo.jpg' %}">
                            </a>
                            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                                <ul class="navbar-nav ml-auto">
                                    <li class="nav-item">
                                        <a class="nav-link" href="#">{% trans 'Contact Us' %}</a>
                                    </li>
                                    <li class="nav-item">
                                        <a class="nav-link" href="#">{% trans 'About' %}</a>
                                    </li>
                                </ul>
                            </div>
                        </nav>
                    </div>
                </div>
            </div>
        </div>
    </div>



{% block content %}
{% endblock %}

        <div class="container-fluid">
                <footer class="footer" style="padding-top: 5px">
                    <div class="fix-width">
                            <div class="col-md-12 sub-footer">
                                <span class="pull-right">
                                    Copyright 2018
                                </span>
                            </div>
                    </div>
                </footer>
        </div>


    {% if messages %}
        <ul class="messages">
            {% for message in messages %}
                <li class="{{ message.tags }}">
                    {{ message|safe }}
                </li>
            {% endfor %}
        </ul>
    {% endif %}




</body>
</html>

templates/base_admin.html
{% load static %}

{% load i18n %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link href="{% static 'css/style.min.css' %}" rel="stylesheet">
    </head>

<body class="skin-megna fixed-layout">
    <div id="main-wrapper">
        <header class="topbar">
            <nav class="navbar top-navbar navbar-expand-md navbar-dark">
                <div class="navbar-header">
                    <a class="navbar-brand" href="{% url 'base:index' %}">
                        <img src="{% static 'images/logo.jpg'%}" width="100%"></a>
                </div>
                <div class="navbar-collapse">
                    <ul class="navbar-nav mr-auto">
                        <li class="nav-item">
                            <a class="nav link navbar-toggler d-block d-md-none waves-effect-dark"
                               href="javascript:void(0)">
                                <i class="ti-menu"></i>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link sidebartoggler d-none d-lg-block d-md-block waves-effect waves-dark"
                               href="javascript:void(0)">
                                <i class="icon-menu">
                                    :
                                </i>
                            </a>
                        </li>
                        <li class="nav-item">
                            <form class="app-search d-none d-md-block d-lg-block">
                                <input type="text" class="form-control" placeholder="Search">
                            </form>
                        </li>
                    </ul>
                </div>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav ml-auto">
                        <li class="nav-item">
                            <a class="nav-link" href="#">{% trans 'Contact Us' %}</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#">{% trans 'About' %}</a>
                        </li>
                    </ul>
                </div>


            </nav>
        </header>
        <aside class="left-sidebar">
            <div class="scroll-sidebar">

                <nav class="sidebar-nav">
                    <ul id="sidebarnav">

                        <li> <a class="waves-effect waves-dark" href="#" aria-expanded="false">My recipes</a></li>

                        <li> <a class="waves-effect waves-dark" href="#" aria-expanded="false">My profile</a></li>

                        <li> <a class="waves-effect waves-dark" href="#" aria-expanded="false">Logout</a></li>

                    </ul>
                </nav>
            </div>

        </aside>
        <div class="page-wrapper">
            <div class="container-fluid">
                {% block content %}
                {% endblock %}
            </div>
        </div>
    </div>




    {% if messages %}
        <ul class="messages">
            {% for message in messages %}
                <li class="{{ message.tags }}">
                    {{ message|safe }}
                </li>
            {% endfor %}
        </ul>
    {% endif %}


</body>
</html>

templates/dashboard.html
{% extends 'base_admin.html' %}

{% load i18n %}


{% block content %}

    <div class="row page-titles">
        <div class="col-md-5 align-self-center">
            <h4 class="text-themecolor">E-cookbook</h4>
        </div>
        <div class="col-md-7 align-self-center text-right">
            <div class="d-flex justify-content-end align-items-center">
                <a href="#" target="_blank" class="btn btn-info d-none d-lg-block m-l-15">
                    {% trans 'Add meal' %}</a>
            </div>
        </div>
    </div>

    <div class="text-center">
        <h2 class="text-title">My meals</h2>
        <div class="card-group">
            {% for meal in meals %}
                <div class="col-lg-4">
                    <div class="card">
                        <div class="card-header">
                            {% for category in meal.categories.all %}{{ category }}<br />{% endfor %}
                        </div>
                        <div class="card-body">
                            <h4 class="card-title">{{ meal.name }}</h4>
                            <p class="card-text">Add later - meal calories</p>
                            <p class="card-text">{{ meal.preparation_time }}</p>
                            <a href="{% url "meals:meal_detail" meal.id %}"
                               class="btn waves-effect waves-info btn-info">{% trans 'View' %}</a>
                            <a href="{% url "meals:meal_delete" meal.id %}"
                               class="btn waves-effect waves-dark btn-dark">{% trans 'Delete' %}</a>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>


{% endblock %}

templates/index.html
{% extends 'base.html' %}

{% load i18n %}

{% block content %}
    <div class="row" id="choose-demo">
        <div class="col-lg-12">
            <div class="light-blue-bg">
                <div class="text-center">
                    <h2 class="text-title">{% trans 'E-Cookbook' %}</h2>
                    <p>{% trans 'Store your favorite recipes with their calories' %}</p>
                    <a href="{% url 'login' %}" target="_blank" class="btn btn-primary btn-rounded">
                        {% trans 'Log in' %}</a>
                    <a href="{% url 'register' %}" target="_blank" class="btn btn-primary btn-rounded">
                        {% trans 'Register' %}</a>

                </div>
            </div>
        </div>
    </div>

    <div class="row m-t-40">
        <div class="col-md-12 m-t-40 m-b-40">
            <div class="fix-width">
                <div class="text-center">
                    <h2 class="text-title">La la land</h2>
                    <p>Srały muchy idzie wiosna, będzia trawa lepiej rosła</p>
                </div>
            </div>
        </div>
    </div>

{% endblock %}