base/urls.py
from django.urls import path
from base.views import index, dashboard

app_name = 'base'

urlpatterns = [
    path('', index, name='index'),
    path('dashboard/', dashboard, name='dashboard'),
]

urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('categories/', include('categories.urls')),
    path('meals/', include('meals.urls')),
    path('products/', include('products.urls')),
    path('users/', include('users.urls')),
    path('', include('authentication.urls')),
    path('', include('base.urls')),
]

if settings.DEBUG:
    import debug_toolbar

    statics = static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) \
        + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

    urlpatterns += [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + statics

users/urls.py
from django.urls import path
from users.views import user_detail, profile_edit

app_name = 'users'

urlpatterns = [

    path('<username>/', user_detail, name='user_detail'),
    path('<username>/edit/', profile_edit, name='profile_edit'),
]

templates/user_account/profile.html
{% extends 'base.html' %}

{% load i18n %}


{% block title %}{% trans 'Your account' %}{% endblock %}


{% block content %}
    <div class="card-header">
        <h3>{% trans 'My  account' %}</h3>

            {% trans 'Username' %}<br />
                {{ user.username }}<br /><br />
            {% trans 'First  name' %}<br />
                {{ user.first_name }}<br /><br />
            {% trans 'Last  name' %}<br />
                {{ user.last_name }}<br /><br />
            {% trans 'E-mail' %}<br />
                {{ user.email }}<br /><br />
            {% trans 'Sex' %}<br />
                {{ user.userprofile.sex }}<br /><br />
            {% trans 'Birth date' %}<br />
                {{ user.userprofile.birth_date }}<br /><br />
            {% if user.userprofile.photo %}
            {% trans 'Photo' %}<br />
                <img src="{{ user.userprofile.photo.url }}" width="200px"><br /><br />
            {% endif %}

            <p><a href="{% url 'users:profile_edit' user.username%}" class="btn btn-success">{% trans 'Edit'%}</a></p>
            <p><a href="{% url 'password_change' %}" class="btn btn-success">{% trans 'Zmień hasło'%}</a></p>
            </div>

    </div>
{% endblock %}

templates/user_account/profile_edit.html
{% extends 'base.html' %}

{% load i18n %}


{% block title %}{% trans 'Editing an account' %}{% endblock %}


{% block content %}
    <div class="card-header">
        <h3>{% trans 'Editing an account' %}</h3>
        <p>{% trans 'You can change your account settings using the form' %}</p>
        <form action="." method="post" enctype="multipart/form-data">
            {% trans 'First name' %}<br />
                {{ user_form.first_name }}<br /><br />
            {% trans 'Last  name' %}<br />
                {{ user_form.last_name }}<br /><br />
            {% trans 'E-mail' %}<br />
                {{ user_form.email }}<br /><br />
            {% trans 'Sex' %}<br />
                {{ profile_form.sex }}<br /><br />
            {% trans 'Birth date' %}<br />
                {{ profile_form.birth_date }}<br /><br />
            {% trans 'Photo' %}<br />
                {{ profile_form.photo }}<br /><br />

            {% csrf_token %}
            <p><input type="submit" class="btn btn-success" value="{% trans 'Save' %}"></p>
        </form>
    </div>

{% endblock %}